services:
  accounts:
    image: "samiyounis01/account:s4"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservices
  loans:
    image: "samiyounis01/loans:s4"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservices
  cards:
    image: "samiyounis01/cards:s4"
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservices
networks:
  microservices:
    driver: "bridge"